name: "Continuous build"

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'continuous*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-16.04
            arch: x86_64
            host: x86_64-linux-gnu
            pkgarch: amd64
            dependencies: g++-multilib nasm wine1.6-dev yasm

          - os: ubuntu-16.04
            arch: i686
            host: i386-linux-gnu
            pkgarch: i386
            dependencies: g++-multilib nasm wine1.6-dev:i386 yasm

          - os: ubuntu-16.04
            arch: armhf
            host: arm-linux-gnueabihf
            pkgarch: armhf
            dependencies: g++-arm-linux-gnueabihf nasm qemu qemu-user-static yasm

          - os: ubuntu-16.04
            arch: aarch64
            host: aarch64-linux-gnu
            pkgarch: arm64
            dependencies: g++-aarch64-linux-gnu nasm qemu qemu-user-static yasm

    runs-on: ${{ matrix.os }}

    steps:
      - name: Add architectures
        run: |
          if [ ${{ matrix.arch }} = x86_64 ]; then
            sudo dpkg --add-architecture i386
          else
            sudo dpkg --add-architecture ${{ matrix.pkgarch }}
          fi

      - name: Prepare sources
        if: ${{ matrix.arch != 'i686' && matrix.arch != 'x86_64' }}
        run: |
          echo "deb [arch=${{ matrix.pkgarch }}] http://ports.ubuntu.com/ubuntu-ports xenial main restricted" | sudo tee --append /etc/apt/sources.list > /dev/null
          echo "deb [arch=${{ matrix.pkgarch }}] http://ports.ubuntu.com/ubuntu-ports xenial-updates main restricted" | sudo tee --append /etc/apt/sources.list > /dev/null
          echo "deb [arch=${{ matrix.pkgarch }}] http://ports.ubuntu.com/ubuntu-ports xenial-security main restricted" | sudo tee --append /etc/apt/sources.list > /dev/null
          sudo sed -i 's/deb http/deb \[arch=amd64,i386\] http/g' /etc/apt/sources.list

      - name: Install dependencies
        run: |
          sudo apt update
          sudo rm /etc/gtk-3.0/settings.ini
          sudo apt remove -y mono-complete libcups2
          sudo apt install -y ${{ matrix.dependencies }}
          sudo apt install -y adwaita-icon-theme gir1.2-gtk-3.0:${{ matrix.pkgarch }} gnome-icon-theme libasound2-dev:${{ matrix.pkgarch }} libblkid1:${{ matrix.pkgarch }} libc-dev:${{ matrix.pkgarch }} libc6-dev:${{ matrix.pkgarch }} libcairo2-dev:${{ matrix.pkgarch }} libcups2:${{ matrix.pkgarch }} libegl1-mesa-dev:${{ matrix.pkgarch }} libexpat1-dev:${{ matrix.pkgarch }} libfontconfig1-dev:${{ matrix.pkgarch }} libfuse2:${{ matrix.pkgarch }} libfreetype6-dev:${{ matrix.pkgarch }} libgdk-pixbuf2.0-dev:${{ matrix.pkgarch }} libglib2.0-dev:${{ matrix.pkgarch }} libgtk-3-dev:${{ matrix.pkgarch }} libgtk-3-0:${{ matrix.pkgarch }} libgtk-3-common:${{ matrix.pkgarch }} libncurses-dev:${{ matrix.pkgarch }} libpango1.0-dev:${{ matrix.pkgarch }} libpcre3-dev:${{ matrix.pkgarch }} libpulse-dev:${{ matrix.pkgarch }} libpulse0:${{ matrix.pkgarch }} libpulse-mainloop-glib0:${{ matrix.pkgarch }} librest-0.7-0:${{ matrix.pkgarch }} libsm-dev:${{ matrix.pkgarch }} libsm6:${{ matrix.pkgarch }} libsndfile1-dev:$ARCH libsndfile1:${{ matrix.pkgarch }} libssl-dev:${{ matrix.pkgarch }} libudev-dev:${{ matrix.pkgarch }} libuuid1:${{ matrix.pkgarch }} libxft-dev:${{ matrix.pkgarch }} linux-libc-dev:${{ matrix.pkgarch }} zlib1g-dev:${{ matrix.pkgarch }}

      - name: Prepare toolchain
        if: ${{ matrix.arch != 'i686' && matrix.arch != 'x86_64' }}
        run: |
          sudo rm -f /usr/bin/gcc /usr/bin/g++ /usr/bin/cpp /usr/bin/ld /usr/bin/strip
          sudo ln -s ${{ matrix.host }}-gcc /usr/bin/gcc
          sudo ln -s ${{ matrix.host }}-g++ /usr/bin/g++
          sudo ln -s ${{ matrix.host }}-cpp /usr/bin/cpp
          sudo ln -s ${{ matrix.host }}-ld /usr/bin/ld
          sudo ln -s ${{ matrix.host }}-strip /usr/bin/strip

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build AppImage
        env:
          AppImageArch: ${{ matrix.arch }}
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          ./packaging/appimage/tools/build-appimage
